### ISSUE TITLE
Boot parameter for CalDavZap language

### ISSUE THREAD

**Issue by reynir** [robur-coop/caldav#43]
In my deployment a request that was made was to change the default language to Danish. I discovered that it's possible via config.js by setting `globalInterfaceLanguage="da_DK"`. I achieved this by making the nginx forward proxy serve a different config.js.

I think we should not try to generate the whole `config.js`, but an easier way to achieve the same is to simply append `globalInterfaceLanguage="da_DK";` at the end of the config.js from the KV store before serving it.

**Comment by hannesm** [comment]
I'm fine with adding a boot parameter for the interfaceLanguage. I don't expect that we need hundreds of configuration options (if it turns out we need a lot, we can revise how to do so).

**Comment by hannesm** [comment]
see #45
